apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pest-store-cert # CHANGE THIS NAME
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: changem@gmail.com # CHANGE TO YOUR EMAIL
    privateKeySecretRef:
      name: pet-store-cert # CHANGE THIS NAME TO MATCH THE METADATA
    solvers:
    - http01:
        ingress:
          class: traefik